//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosDemo.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string C_name { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string notes { get; set; }
        public string image { get; set; }
    }
}
